version: '3'
services:
  puisiku-soap-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:${MYSQL_PORT}"
    volumes:
      - mysql_db_volume:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - puisiku

  puisiku-soap-service:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      puisiku-soap-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - puisiku
    restart: on-failure:5

volumes:
  mysql_db_volume:

networks:
  puisiku:
    external: true
